/** @format */

window.LOVE_ARCHIVE_DEFAULTS = {
  brand: "our little archive",
  title: "A little corner for us.",
  intro: "Kumpulan momen kecil yang ternyata jadi alasan paling besar untuk tersenyum hari ini.",
  quote: "Hal-hal sederhana terasa istimewa kalau dilakukan sama kamu.",
  letter: "Terima kasih sudah hadir di hari-hari biasa dan membuatnya terasa seperti halaman favorit. Semoga kita selalu menemukan alasan kecil untuk pulang, tertawa, dan memilih satu sama lain lagi.",
  signature: "love, your favorite person",
  heroKicker: "a tiny love archive",
  heroYear: "2024—forever",
  heroLink: "scroll to memories",
  heroCaption: "the best kind of ordinary",
  heroSticker: "good<br />days",
  heroNote: "made with a lot of love",
  quoteByline: "— catatan kecil, untuk selamanya",
  momentsKicker: "01 / our timeline",
  momentsTitle: "Little moments,<br /><em>big feelings.</em>",
  momentsAside: "Dari obrolan random sampai hari yang tidak ingin kita lupakan.",
  notesKicker: "02 / open when",
  notesTitle: "Notes for<br /><em>your pocket.</em>",
  notesAside: "Buka satu-satu. Ada pesan rahasia kecil di tiap kertas.",
  playlistKicker: "03 / our soundtrack",
  playlistTitle: "Press play,<br /><em>feel it again.</em>",
  playlistAside: "Soundtrack untuk perjalanan pulang, malam panjang, dan semua jeda di antaranya.",
  wishlistKicker: "04 / someday list",
  wishlistTitle: "Things we<br /><em>should do.</em>",
  wishlistAside: "Rencana kecil yang boleh dicentang pelan-pelan.",
  sharedNotesKicker: "05 / our little mailbox",
  sharedNotesTitle: "Leave a note<br /><em>for us.</em>",
  sharedNotesAside: "Tulis sesuatu yang ingin kamu simpan hari ini. Catatan ini tinggal di browser kalian.",
  letterKicker: "a letter, not a goodbye",
  footerLeft: "made for the two of us",
  footerMark: "♡",
  footerRight: "keep the good stuff",
  heroImage: "https://images.unsplash.com/photo-1518199266791-5375a83190b7?auto=format&fit=crop&w=900&q=85",
  moments: [
    { date: "14.02.24", title: "The first hello", text: "Satu sapaan kecil yang diam-diam mengubah banyak hal.", image: "https://images.unsplash.com/photo-1522673607200-164d1b6ce486?auto=format&fit=crop&w=700&q=85", tone: "lavender" },
    { date: "03.03.24", title: "Coffee & conversations", text: "Kopi dingin, obrolan hangat, dan lupa waktu.", image: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=700&q=85", tone: "peach" },
    { date: "28.04.24", title: "A soft Sunday", text: "Tidak ada rencana. Justru jadi hari terbaik.", image: "https://images.unsplash.com/photo-1474552226712-ac0f0961a954?auto=format&fit=crop&w=700&q=85", tone: "butter" },
  ],
  notes: [
    { label: "open when...", title: "you need a hug", text: "Bayangkan aku memelukmu erat. Kamu tidak harus kuat setiap saat, ya.", color: "lilac" },
    { label: "open when...", title: "you miss me", text: "Aku juga sedang melihat bulan yang sama. Kita tidak sejauh itu.", color: "yellow" },
    { label: "open when...", title: "you feel stuck", text: "Pelan-pelan saja. Kita sudah melewati banyak hal dan kamu selalu berhasil.", color: "pink" },
  ],
  tracks: [
    { title: "Sweet disposition", artist: "The Temper Trap", src: "" },
    { title: "Everywhere", artist: "Fleetwood Mac", src: "" },
    { title: "Bloom", artist: "The Paper Kites", src: "" },
  ],
  wishlist: [
    { title: "sunrise breakfast", detail: "bangun sebelum kota ramai", done: false },
    { title: "tiny road trip", detail: "pilih jalan tanpa tujuan", done: false },
    { title: "make a photo book", detail: "cetak semua cerita kecil", done: false },
    { title: "learn something new", detail: "saling jadi murid lagi", done: false },
  ],
};
